### ISSUE TITLE
check sj spawning related params to see if we need to add proxy values 

### ISSUE THREAD

**Issue by ErinCain** [Reorienting-to-Recovery/DSMhabitat#7]
Look through all spawning related params (eg. egg to fry survival parms, get spawning adult params) and if NA or 0 for any SJ values create a list that we can review and figure out what to use as a proxy.

**Comment by ErinCain** [comment]
List of params that need modification: 
- fallRunDSM::params$mean_egg_temp_effect

**Comment by MaddeeRubenson** [comment]
**Spawning Adults**

- fallRunDSM::params$prop_flow_natal
- fallRunDSM::params$south_delta_routed_watersheds ??
- fallRunDSM::params$cross_channel_stray_rate
- fallRunDSM::params$stray_rate
- fallRunDSM::params$tisdale_bypass_watershed ??
- fallRunDSM::params$yolo_bypass_watershed ??
- fallRunDSM::params$migratory_temperature_proportion_over_20
- fallRunDSM::params$degree_days
- fallRunDSM::params$prob_nest_scoured - currently 0.1, unsure if we want to modify
- fallRunDSM::params$hatchery_allocation
- fallRunDSM::params$natural_adult_removal_rate

**Egg to Fry Survival**

- fallRunDSM::params$mean_egg_temp_effect

**Comment by ErinCain** [comment]
Reviewed and I think the ones we need to change are: 
- fallRunDSM::params$prop_flow_natal (calculate for upper sj) 
- fallRunDSM::params$south_delta_routed_watersheds (San Joaquin should change from 0 to 1) 
- fallRunDSM::params$cross_channel_stray_rate - can keep at 0.0
- fallRunDSM::params$stray_rate (San Joaquin should change from 0 - .04) 
- fallRunDSM::params$migratory_temperature_proportion_over_20 (calculate for san joaquin) 
- fallRunDSM::params$degree_days (calculate for San Joaquin) 
- fallRunDSM::params$hatchery_allocation (TODO add in - ask Mark) - ask rene (0 might be okay) 
- fallRunDSM::params$natural_adult_removal_rate (TODO are fish removed? If so add in)  - ask rene (0 might be okay) 
- fallRunDSM::params$mean_egg_temp_effect (TODO add in - ask Mark)

**Comment by ErinCain** [comment]
Only have to do for spring.

**Comment by MaddeeRubenson** [comment]
* **proportion_flow_natal** - this is currently a value of 1 which I believe makes sense since it represents proportion flows at tributary junction and the tributary junction of the SJ is the SJ. I can't calculate for the Upper SJ because the flows remain the same. 
* `springRunDSM::params$south_delta_routed_watersheds` updated to `DSMhabitat::spring_south_delta_routed_watersheds`
* kept `cross_channel_stray_rate` at 0
* `stray_rate` updated to `0.03846154`
* changed `migratory_temperature_proportion_over_20` to `migratory_temperature_proportion_over_20_sr`
* `degree_days` changed to `degree_days_sr` in DSMtemperature 

I don't remember what we decided for these, do you?: 

- springRunDSM::params$hatchery_allocation - keep at zero
- springRunDSM::params$natural_adult_removal_rate - keep at zero
- springRunDSM::params$mean_egg_temp_effect - update to be the same as the Tuolumne River.
